include:
  - board: nice_nano_v2
    shield: sofle_left
    snippet: studio-rpc-usb-uart
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: nice_nano_v2
    shield: sofle_right
